test console in push.yml #48

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -5,72 +5,80 @@ on:
     branches: [ "main" ]
 
 jobs:
-  build:
+#  build:
+#
+#    runs-on: ubuntu-latest
+#    permissions:
+#      contents: read
+#
+#    steps:
+#    - uses: actions/checkout@v4
+#    - name: Set up JDK 17
+#      uses: actions/setup-java@v4
+#      with:
+#        java-version: '17'
+#        distribution: 'temurin'
+#
+#    - name: Setup Gradle
+#      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
+#
+#    - name: Build with Gradle Wrapper
+#      run: ./gradlew build
 
+#  dependency-submission:
+#
+#    runs-on: ubuntu-latest
+#    permissions:
+#      contents: write
+#
+#    steps:
+#    - uses: actions/checkout@v4
+#    - name: Set up JDK 17
+#      uses: actions/setup-java@v4
+#      with:
+#        java-version: '17'
+#        distribution: 'temurin'
+#
+#    - name: Generate and submit dependency graph
+#      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
+#
+#  apk-release:
+#    runs-on: ubuntu-latest
+#    steps:
+#    - uses: actions/checkout@v4
+#    - name: Set up JDK 17
+#      uses: actions/setup-java@v4
+#      with:
+#        java-version: '17'
+#        distribution: 'temurin'
+#
+#    - name: Build debug APK
+#      run: ./gradlew assembleDebug --stacktrace
+#
+#    - name: Set environment variables
+#      run: |
+#        echo VERSION_NAME=$(${{ github.workspace }}/gradlew -q printVersionName) >> $GITHUB_ENV
+#        echo APPLICATION_NAME=$(${{ github.workspace }}/gradlew -q printApplicationName) >> $GITHUB_ENV
+#
+#    - name: Fail if version is empty
+#      if: ${{ env.VERSION_NAME == '' }}
+#      run: exit 1
+#
+#    - name: Fail if app name is empty
+#      if: ${{ env.APPLICATION_NAME == '' }}
+#      run: exit 1
+#
+#    - name: Create Release and Upload APK to Release
+#      run: |
+#        cp app/build/outputs/apk/debug/app-debug.apk ${{ env.APPLICATION_NAME }}-debug-${{ env.VERSION_NAME }}.apk
+#        gh release create v${{ env.VERSION_NAME }} ${{ env.APPLICATION_NAME }}-debug-${{ env.VERSION_NAME }}.apk
+#      env:
+#        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  test:
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-
     steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
+    - uses: actions/github-script@v7
       with:
-        java-version: '17'
-        distribution: 'temurin'
-
-    - name: Setup Gradle
-      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
-
-    - name: Build with Gradle Wrapper
-      run: ./gradlew build
-
-  dependency-submission:
-
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
-
-    - name: Generate and submit dependency graph
-      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
-
-  apk-release:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
-
-    - name: Build debug APK
-      run: ./gradlew assembleDebug --stacktrace
-        
-    - name: Set environment variables
-      run: |
-        echo VERSION_NAME=$(${{ github.workspace }}/gradlew -q printVersionName) >> $GITHUB_ENV
-        echo APPLICATION_NAME=$(${{ github.workspace }}/gradlew -q printApplicationName) >> $GITHUB_ENV
-
-    - name: Fail if version is empty
-      if: ${{ env.VERSION_NAME == '' }}
-      run: exit 1
-
-    - name: Fail if app name is empty
-      if: ${{ env.APPLICATION_NAME == '' }}
-      run: exit 1
-
-    - name: Create Release and Upload APK to Release
-      run: |
-        cp app/build/outputs/apk/debug/app-debug.apk ${{ env.APPLICATION_NAME }}-debug-${{ env.VERSION_NAME }}.apk
-        gh release create v${{ env.VERSION_NAME }} ${{ env.APPLICATION_NAME }}-debug-${{ env.VERSION_NAME }}.apk
-      env:
-        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        script: |
+          console.log(context.issue.number)
